plugins {
    id 'java'
    id "org.teavm" version "0.13.0"
    id 'war'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation teavm.libs.jsoApis
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

teavm {
    all {
        mainClass = "jagex2.client.Client"
    }
    js {
        addedToWebApp = true
    }
    wasmGC {
        addedToWebApp = true
    }
}
